version: "3.4"

services:
  api:
    image: "${DOCKER_REGISTRY-}compilemeapi"
    build:
      context: .
      dockerfile: compile.me.api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - nsqd

  management:
    image: "${DOCKER_REGISTRY-}compilemeworkermanagement"
    build:
      context: .
      dockerfile: Compile.Me.Worker.Management/Dockerfile
    networks:
      - default
    depends_on:
      - api
      - nsqd

#  worker:
#    image: "${DOCKER_REGISTRY-}compilemeworkerservice"
#    build:
#      context: .
#      dockerfile: compile.me.worker.service/Dockerfile
#    networks:
#      - default
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - source: '\\.\pipe\docker_engine'
#        target: '\\.\pipe\docker_engine'
#        type: npipe
#    depends_on:
#      - nsqd

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: compile-me
    ports:
      - "54320:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - default

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - default

  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - default

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - default

networks:
  default:

